---
apiVersion: v1
kind: Secret
metadata:
  name: megatest35-poi-map-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/rhdh-atl/megatest35-frontend-gitops
